// flow-typed signature: 691ef5a998e1915496df3640f0eef21b
// flow-typed version: <<STUB>>/imagemin-webp-webpack-plugin_v^3.1.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin-webp-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagemin-webp-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'imagemin-webp-webpack-plugin/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'imagemin-webp-webpack-plugin/plugin.js' {
  declare module.exports: $Exports<'imagemin-webp-webpack-plugin/plugin'>;
}
