// flow-typed signature: db161a363e7e46f0a3bbb8add671d66c
// flow-typed version: <<STUB>>/modern-normalize_v^0.5.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'modern-normalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'modern-normalize' {
  declare module.exports: any;
}
