// flow-typed signature: 10201e03237549c1053bf83ac8dea51f
// flow-typed version: <<STUB>>/react-svg-inline_v^2.1.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-svg-inline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-svg-inline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-svg-inline/lib/index' {
  declare module.exports: any;
}

declare module 'react-svg-inline/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-svg-inline/lib/index.js' {
  declare module.exports: $Exports<'react-svg-inline/lib/index'>;
}
declare module 'react-svg-inline/src/index.js' {
  declare module.exports: $Exports<'react-svg-inline/src/index'>;
}
