// flow-typed signature: 20775ab0ba073725c46f27ce4097fb92
// flow-typed version: <<STUB>>/react-inlinesvg_v^0.8.4/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-inlinesvg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-inlinesvg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-inlinesvg/es/index' {
  declare module.exports: any;
}

declare module 'react-inlinesvg/es/utils' {
  declare module.exports: any;
}

declare module 'react-inlinesvg/lib/index' {
  declare module.exports: any;
}

declare module 'react-inlinesvg/lib/utils' {
  declare module.exports: any;
}

declare module 'react-inlinesvg/src/index' {
  declare module.exports: any;
}

declare module 'react-inlinesvg/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-inlinesvg/es/index.js' {
  declare module.exports: $Exports<'react-inlinesvg/es/index'>;
}
declare module 'react-inlinesvg/es/utils.js' {
  declare module.exports: $Exports<'react-inlinesvg/es/utils'>;
}
declare module 'react-inlinesvg/lib/index.js' {
  declare module.exports: $Exports<'react-inlinesvg/lib/index'>;
}
declare module 'react-inlinesvg/lib/utils.js' {
  declare module.exports: $Exports<'react-inlinesvg/lib/utils'>;
}
declare module 'react-inlinesvg/src/index.js' {
  declare module.exports: $Exports<'react-inlinesvg/src/index'>;
}
declare module 'react-inlinesvg/src/utils.js' {
  declare module.exports: $Exports<'react-inlinesvg/src/utils'>;
}
