// flow-typed signature: e66843b05efa9093b2ab83280ae75b72
// flow-typed version: <<STUB>>/webapp-webpack-plugin_v^2.6.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webapp-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webapp-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webapp-webpack-plugin/src/compat' {
  declare module.exports: any;
}

declare module 'webapp-webpack-plugin/src/compiler' {
  declare module.exports: any;
}

declare module 'webapp-webpack-plugin/src/index' {
  declare module.exports: any;
}

declare module 'webapp-webpack-plugin/src/loader' {
  declare module.exports: any;
}

declare module 'webapp-webpack-plugin/src/oracle' {
  declare module.exports: any;
}

declare module 'webapp-webpack-plugin/src/rule_loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webapp-webpack-plugin/src/compat.js' {
  declare module.exports: $Exports<'webapp-webpack-plugin/src/compat'>;
}
declare module 'webapp-webpack-plugin/src/compiler.js' {
  declare module.exports: $Exports<'webapp-webpack-plugin/src/compiler'>;
}
declare module 'webapp-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'webapp-webpack-plugin/src/index'>;
}
declare module 'webapp-webpack-plugin/src/loader.js' {
  declare module.exports: $Exports<'webapp-webpack-plugin/src/loader'>;
}
declare module 'webapp-webpack-plugin/src/oracle.js' {
  declare module.exports: $Exports<'webapp-webpack-plugin/src/oracle'>;
}
declare module 'webapp-webpack-plugin/src/rule_loader.js' {
  declare module.exports: $Exports<'webapp-webpack-plugin/src/rule_loader'>;
}
