// flow-typed signature: 63781a449f02f05dc9216ba8790c62ae
// flow-typed version: <<STUB>>/webfont-webpack-plugin_v^0.2.2/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webfont-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webfont-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webfont-webpack-plugin/dist/WebfontPlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webfont-webpack-plugin/dist/WebfontPlugin.js' {
  declare module.exports: $Exports<'webfont-webpack-plugin/dist/WebfontPlugin'>;
}
